Feat/pytest
aws-samples/generative-ai-cdk-constructs-samples pull request #59
Opened 2024-05-14 20:40 UTC by dineshSajwan

*Issue #, if available:*

*Description of changes:*
1. updated bedrock sample with bedrock constructs in cdklabs.generative_ai_cdk_construct
2. Updated python sample for integration test and bedrock constructs 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-05-15 18:29 UTC, scottschreckengaust approved these changes

2024-05-15 18:32 UTC, scottschreckengaust requested changes
testing

2024-05-16 14:22 UTC, krokoko commented on samples/bedrock-agent/package.json
>      "@aws-cdk/aws-lambda-python-alpha": "2.124.0-alpha.0",
2.141

2024-05-16 14:56 UTC, dineshSajwan commented on samples/bedrock-agent/package.json
>      "@aws-cdk/aws-lambda-python-alpha": "2.124.0-alpha.0",
done

2024-06-04 17:56 UTC, scottschreckengaust approved these changes

2024-06-04 17:56 UTC, merged